spring:
  application:
    name: zipkin-server
  datasource:
    url: jdbc:mysql://172.31.1.100:3306/coin?useUnicode=true&characterEncoding=UTF-8
    username: kaifa
    password: y9k(s*DlexrrYrq$m4W
    driverClassName: com.mysql.jdbc.Driver
server:
  port: 8090

zipkin:
  storage:
    type: mysql

