spring:
  application:
    name: zipkin-server
  datasource:
    url: jdbc:mysql://192.168.0.101:3306/market?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: asdzxczxc
    driverClassName: com.mysql.jdbc.Driver
server:
  port: 8090

zipkin:
  storage:
    type: mysql

