eureka:
    instance:
        prefer-ip-address: true
        leaseRenewalIntervalInSeconds: 10
        metadataMap:
          cluster: ECO-LITE-SERVICE
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://peer1:8084/eureka/,http://peer2:8085/eureka/,http://peer3:8086/eureka/
server:
  port: 8011
  context-path: /eco-lite-service
   
   
#wallet:
#  rootPath: C:\\ecowallet
#  privateKey: cRBMGxnVXLgydAGHDFTLtFJpCdiLUt5zCTWEn2baJm4m7ubuiBa3
spring:
    application:
        name: eco-lite-service
    datasource:
      readSize: 1
        # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.1.136:3306/market?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: asdzxczxc
      validationQuery: SELECT 1 FROM DUAL

      

#指定log的配置文件，以及记录Spring Boot的log级别  
logging:
  config: classpath:logback.xml
  