
spring:
  messages:
    basename: i18n/messages
  cache:
    type: redis
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    max-active: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      stat-view-servlet:
        allow: true
  redis:
    host: redis
    port: 6479
    pool:
      max-active: 8
      min-idle: 0
      max-idle: 8
      max-wait: -1
---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://192.168.1.136:3306/market?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: asdzxczxc
  redis:
    host: redis
    port: 6479
ETH:
  hot:
    address: "0x48e64f4a2399dD330f7A23d0E8E48358Fec02d14"
    privateKey: 8B8371FC406226C13BBDE4768CA9FEFD0D54BB9A078CD3954BE506259A576AE33BB05916B96E5A99AA729ABF37BDEBF41FE8C53297860612066E0B7053A7E6A33125A2953A164BD754AF4723BDE3C865
---
spring:
  profiles: default, dev
  datasource:
    url: jdbc:mysql://192.168.1.136:3306/market?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: asdzxczxc
  redis:
    host: redis
    port: 6479
ETH:
  hot:
    address: "0x48e64f4a2399dD330f7A23d0E8E48358Fec02d14"
    privateKey: 8B8371FC406226C13BBDE4768CA9FEFD0D54BB9A078CD3954BE506259A576AE33BB05916B96E5A99AA729ABF37BDEBF41FE8C53297860612066E0B7053A7E6A33125A2953A164BD754AF4723BDE3C865
